Science ahmed chef
learningequality/sushi-chef-science-ahmed-al-hoot-ar pull request #1
Opened 2018-12-07 15:01 UTC by elaeon

2019-01-11 19:24 UTC, ivanistheone requested changes

2019-01-11 19:24 UTC, ivanistheone commented on sushichef.py
> +                description="""Mr. Ahmad Al-Hoot from Egypt provides 13-16 year old learners with video lessons covered in several national curricula across the region in chemistry, biology and geolo
@elaeon
Could you please change the description to the Arabic text from here: https://docs.google.com/document/d/1PQi6y-A4ZYQOepUpe4lldK3gbquUSy3e9NLEGeIex8c/edit#bookmark=id.unqhypiqmiic

I see you already changed the title, so after that this one looks ready to go!

2019-02-28 23:05 UTC, kollivier approved these changes

2019-02-28 23:05 UTC, kollivier commented on sushichef.py
> +                ydl.add_default_info_extractors()
What does this do? is this something we should add to YouTubeResource.get_resource_info as well?

2019-02-28 23:05 UTC, kollivier commented on sushichef.py
> +                    playlist_videos_url.append(entry["webpage_url"])
BTW, YouTubeResource._format_for_ricecooker will make this change along with a few others. (It's run automatically by get_resource_info)

2019-02-28 23:05 UTC, kollivier commented on utils.py
> +def dir_exists(filepath):
If you have methods like this that most of your chefs use, please feel free to submit them to pressurecooker so that there is only one copy of this code shared by all the chefs.

2019-02-28 23:05 UTC, kollivier commented on utils.py
> +def get_name_from_url(url):
Are these methods called by the code?

2019-02-28 23:05 UTC, kollivier commented on utils.py
> +def dir_exists(filepath):
BTW, there is now a pressurecooker.utils module for these to go in.

2019-02-28 23:05 UTC, kollivier commented on utils.py
> +def dir_exists(filepath):
Oh, one more comment. Pressurecooker also supports 2.7 so we'd need this to not use pathlib.Path. Is there any reason not to do os.path.isfile and os.path.isdir for these?

2019-02-28 23:07 UTC, merged